performance:
  hpc: false  # 是否在高性能计算集群上运行
  cpu_cores: 10  # CPU核心数
  memory: 50G  # 内存大小
  chunk_size: 100000 # 输出数据时的分块大小，避免内存溢出的问题，建议最大分块100000
  processes: 10 # 每个任务并行处理的进程数
  walltime: 48:00:00  # 最大运行时间
  job_extra: []  # 额外的作业参数，可为空，示例 ["#SBATCH -J efgh", "#SBATCH -p normal", "#SBATCH -e id.error"，"#SBATCH -o id.out","--exclusive"]
  jobs: 10 # 每个作业的任务数
input:
  vcz_path: ./data/mouse_hs1940.vcz  # VCF或VCF.GZ基因型文件路径（建议使用绝对路径）
  pheno_path: ./data/mouse_hs1940.csv  # 表型CSV文件路径（建议使用绝对路径）
  gff_path: ./data/gencode.vM37.basic.annotation.gff3  # GFF文件路径（建议使用绝对路径）

output:
  outdir: ./results                                # 输出目录（建议使用绝对路径）

qc:
  maf: 0.01                                          # 最小等位基因频率（MAF）过滤阈值
  variant_missing: 0.02                              # 变异位点缺失率过滤阈值
  sample_missing:  0.02                              # 样本缺失率过滤阈值
  hwe: 1e-6                                          # Hardy-Weinberg平衡检验p值过滤阈值
pca:
  pcs: 3                                             # 主成分分析（PCA）计算的主成分数量
gwas:
  run_gwas: false                                  # 是否运行GWAS分析
  traits: CD8                                    # 需要分析的表型列名，示例：CD8, MCH
  covariates:                                        # 需要分析的协变量列表（留空则不使用协变量），示例格式：covariates_1,covariates_2
  models: linear_regression                     # 支持 linear_regression, regenie 或两者组合，示例格式：linear_regression, regenie
  manhattan:  #曼哈顿图输出配置
    chrom_colors: ["#1f77b4", "#ff7f0e"]  # 染色体交替颜色
    threshold_lines:  #阈值线
      - value: 5 # 默认一条黑色实线，在Y轴5的位置上
        style: solid
        color: "#000000"
#      - value: 10 # 最多支持两条阈值线
#        style: dashed
#        color: "#000000"
    point_colors: # 点的颜色
      below: "#1f77b4"
      above: "#d62728"
      between: "#2ca02c"
haplotype:
  run_haplotype: true  # 是否运行单倍型分析
  gene_name: "Xkr4"  # 需要分析的基因名称
  phase_method: ignore_het  # 可选: ignore_het, random_het, mode_het
  phenotype: "CD8"  # 需要分析的表型列名
